CREATE DATABASE BAI1
USE BAI1

CREATE TABLE TACGIA
(
	MaTG char(5) NOT NULL,
	HoTen varchar(20),
	DiaChi varchar(50),
	NgSinh smalldatetime,
	SoDT varchar(15),
	CONSTRAINT TACGIA_PK PRIMARY KEY (MaTG)
)

CREATE TABLE SACH
(
	MaSach char(5) NOT NULL,
	TenSach varchar(25),
	TheLoai varchar(25),
	CONSTRAINT SACH_PK PRIMARY KEY (MaSach)
)

CREATE TABLE TACGIA_SACH
(
	MaTG char(5) NOT NULL,
	MaSach char(5) NOT NULL,
	CONSTRAINT TGSACH_PK PRIMARY KEY (MaTG, MaSach),
	CONSTRAINT TACGIA_FK FOREIGN KEY (MaTG) REFERENCES TACGIA(MaTG),
	CONSTRAINT SACH_FK FOREIGN KEY (MaSach) REFERENCES SACH(MaSach)
)

CREATE TABLE PHATHANH
(
	MaPH char(5) NOT NULL,
	MaSach char(5) NOT NULL,
	NgayPH smalldatetime,
	SoLuong int,
	NhaXuatBan varchar(20),
	CONSTRAINT PHATHANH_PK PRIMARY KEY (MaPH),
	CONSTRAINT PHATHANHSACH_FK FOREIGN KEY (MaSach) REFERENCES SACH(MaSach)
)

-- Cau 2 --
-- Cau 2.1 --
CREATE TRIGGER ins_up_CAU2 ON PHATHANH
FOR INSERT, UPDATE
AS
BEGIN
	DECLARE @NGAYPH smalldatetime, @NGSINH smalldatetime
	DECLARE @MASACH char(5), @MATG char(5)
	SELECT @NGAYPH, @MASACH FROM INSERTED
	SELECT @MATG = MaTG FROM TACGIA_SACH WHERE @MASACH = MaSach
	SELECT @NGSINH = NgSinh FROM TACGIA WHERE @MATG = MaTG
	IF (@NGAYPH > @NGSINH)
	BEGIN
		PRINT 'THAO TAC THANH CONG!!'
	END
	ELSE
	BEGIN
		PRINT 'NGAY PHAT HANH PHAI LON HON NGAY SINH CUA TAC GIA!!'
		ROLLBACK TRAN
	END
END

-- Cau 2.2 --
CREATE TRIGGER ins_up_CAU2point2 ON PHATHANH
FOR INSERT, UPDATE
AS
BEGIN
	DECLARE @MASACH char(5)
	DECLARE @THELOAI varchar(25)
	DECLARE @NHAXUATBAN varchar(25)
	SELECT @NHAXUATBAN, @MASACH FROM INSERTED
	SELECT @THELOAI = TheLoai FROM SACH WHERE @MASACH = MaSach
	IF (@THELOAI = 'Giao Khoa' AND @NHAXUATBAN = 'Giao Duc')
	BEGIN
		PRINT 'THAO TAC THANH CONG'
	END
	ELSE
	BEGIN
		PRINT 'Sach giao khoa chi duoc phat hanh boi nha xuat ban Giao Duc'
		ROLLBACK TRAN
	END
END

-- Cau 3 --
-- Cau 3.1 --
SELECT TACGIA.MaTG, HoTen, SoDT
FROM TACGIA
JOIN TACGIA_SACH ON TACGIA.MaTG = TACGIA_SACH.MaTG
JOIN SACH ON TACGIA_SACH.MaSach = SACH.MaSach
JOIN PHATHANH ON SACH.MaSach = PHATHANH.MaSach
WHERE TheLoai = 'Van hoc' AND NhaXuatBan = 'Tre'

-- Cau 3.2 -- 
SELECT TOP 1 NhaXuatBan, COUNT(DISTINCT TheLoai) AS SoTheLoai
FROM PHATHANH
JOIN SACH ON PHATHANH.MaSach = SACH.MaSach
GROUP BY NhaXuatBan
ORDER BY SoTheLoai DESC

-- Cau 3.3 --
SELECT NhaXuatBan, TACGIA.MaTG, HoTen
FROM (
    SELECT NhaXuatBan, MaTG, COUNT(*) as SoLanPhatHanh,
    RANK() OVER(PARTITION BY NhaXuatBan ORDER BY COUNT(*) DESC) as rank
    FROM PHATHANH
    JOIN SACH ON PHATHANH.MaSach = SACH.MaSach
    JOIN TACGIA_SACH ON SACH.MaSach = TACGIA_SACH.MaSach
    GROUP BY NhaXuatBan, TACGIA_SACH.MaTG
) as TG_PH
JOIN TACGIA ON TG_PH.MaTG = TACGIA.MaTG
WHERE rank = 1


