CREATE DATABASE BAI4
USE BAI4

CREATE TABLE KHACHHANG
(
	MAKH CHAR(5) NOT NULL,
	HOTEN VARCHAR(30),
	DIACHI VARCHAR(30),
	SODT VARCHAR(15),
	LOAIKH VARCHAR(10),
	CONSTRAINT KH_PK PRIMARY KEY (MAKH)
)

CREATE TABLE BANG_DIA
(
	MABD CHAR(5) NOT NULL,
	TENBD VARCHAR(25),
	THELOAI VARCHAR(25),
	CONSTRAINT BD_PK PRIMARY KEY (MABD)
)

CREATE TABLE PHIEUTHUE
(
	MAPT CHAR(5) NOT NULL,
	MAKH CHAR(5) NOT NULL,
	NGAYTHUE SMALLDATETIME,
	NGAYTRA SMALLDATETIME,
	SOLUONGTHUE INT,
	CONSTRAINT PT_PK PRIMARY KEY (MAPT),
	CONSTRAINT PT_KH_PT FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH)
)

CREATE TABLE CHITIET_PM
(
	MAPT CHAR(5) NOT NULL,
	MABD CHAR(5) NOT NULL,
	CONSTRAINT CTPM_PK PRIMARY KEY (MAPT, MABD),
	CONSTRAINT CTPM_PT_FK FOREIGN KEY (MAPT) REFERENCES PHIEUTHUE(MAPT),
	CONSTRAINT CTPM_BD_FK FOREIGN KEY (MABD) REFERENCES BANG_DIA(MABD)
)

-- CAU 2 --
-- CAU 2.1 --
ALTER TABLE BANG_DIA ADD CONSTRAINT KT_TL CHECK (THELOAI IN ('CA NHAC', 'PHIM HANH DONG', 'PHIM TINH CAM', 'PHIM HOAT HINH'))

-- CAU 2.2 --
CREATE TRIGGER CAU2POINT2 ON PHIEUTHUE
FOR INSERT, UPDATE
AS
BEGIN
	DECLARE @MAKH CHAR(5)
	DECLARE @LOAIKH VARCHAR(10)
	DECLARE @SLTHUE INT
	SELECT @MAKH = MAKH, @SLTHUE = SOLUONGTHUE FROM inserted
	SELECT @LOAIKH = LOAIKH FROM KHACHHANG WHERE @MAKH = MAKH
	IF (@LOAIKH = 'VIP')
	BEGIN
		UPDATE PHIEUTHUE
		SET @SLTHUE = 5 
		WHERE @MAKH = MAKH
	END
	ELSE
	BEGIN
		PRINT 'KHACH HANG NAY KHONG PHAI VIP'
		ROLLBACK TRAN
	END
END

-- CAU 3 --
-- CAU 3.1 --
SELECT KHACHHANG.MAKH, HOTEN
FROM KHACHHANG
JOIN PHIEUTHUE ON KHACHHANG.MAKH = PHIEUTHUE.MAKH
JOIN CHITIET_PM ON PHIEUTHUE.MAPT = CHITIET_PM.MAPT
JOIN BANG_DIA ON CHITIET_PM.MABD = BANG_DIA.MABD
WHERE THELOAI = 'TINH CAM' AND SOLUONGTHUE > 3

-- CAU 3.2 --
SELECT TOP 1 WITH TIES KHACHHANG.MAKH, HOTEN, COUNT(DISTINCT MABD) AS SOLUONGBANGDIA
FROM KHACHHANG
JOIN PHIEUTHUE ON KHACHHANG.MAKH = PHIEUTHUE.MAKH
JOIN CHITIET_PM ON PHIEUTHUE.MAPT = CHITIET_PM.MAPT
GROUP BY KHACHHANG.MAKH, HOTEN
ORDER BY SOLUONGBANGDIA DESC

-- CAU 3.3 --
SELECT THELOAI, KH.HOTEN, KH.MAKH
FROM (
    SELECT THELOAI, MAKH, COUNT(*) as SoLanThue,
    RANK() OVER(PARTITION BY THELOAI ORDER BY COUNT(*) DESC) as rank
    FROM BANG_DIA BD
    JOIN CHITIET_PM CTPM ON BD.MABD = CTPM.MABD
    JOIN PHIEUTHUE PT ON CTPM.MAPT = PT.MAPT
    GROUP BY THELOAI, PT.MAKH
) as KH_TH
JOIN KHACHHANG KH ON KH_TH.MAKH = KH.MAKH
WHERE rank = 1


