CREATE DATABASE DETHI01
USE DETHI01

CREATE TABLE KHACHHANG
(
	MAKH CHAR(4) NOT NULL,
	TENKH VARCHAR(50),
	DIACHI VARCHAR(15),
	LOAIKH VARCHAR(30),
	CONSTRAINT KH_PK PRIMARY KEY (MAKH)
)

CREATE TABLE LOAICAY
(
	MALC CHAR(4) NOT NULL,
	TENLC VARCHAR(50),
	XUATXU VARCHAR(15),
	GIA MONEY,
	CONSTRAINT LC_PK PRIMARY KEY (MALC)
)

CREATE TABLE HOADON
(
	SOHD CHAR(5) NOT NULL,
	NGHD SMALLDATETIME,
	MAKH CHAR(4) NOT NULL,
	KHUYENMAI INT,
	CONSTRAINT HD_PK PRIMARY KEY (SOHD),
	CONSTRAINT HD_KH_FK FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH)
)

CREATE TABLE CTHD
(
	SOHD CHAR(5) NOT NULL,
	MALC CHAR(4) NOT NULL,
	SOLUONG INT,
	CONSTRAINT CTHD_PK PRIMARY KEY (SOHD,MALC),
	CONSTRAINT CTHD_HD_FK FOREIGN KEY (SOHD) REFERENCES HOADON(SOHD),
	CONSTRAINT CTHD_LC_FK FOREIGN KEY (MALC) REFERENCES LOAICAY(MALC)
)

INSERT INTO KHACHHANG(MAKH, TENKH, DIACHI, LOAIKH)
VALUES
('KH01', 'Liz Kim Cuong', 'Ha Noi', 'Vang lai'),
('KH02', 'Ivone Dieu Linh', 'Da Nang', 'Thuong xuyen'),
('KH03', 'Emma Nhat Khanh', 'TP.HCM', 'Vang lai');

INSERT INTO LOAICAY(MALC, TENLC, XUATXU, GIA)
VALUES
('LC01', 'Xuong rong tai tho', 'Mexico', 180000),
('LC02', 'Sen thach ngoc', 'Anh', 300000),
('LC03', 'Ba mau rau', 'Nam Phi', 270000);

INSERT INTO HOADON(SOHD, NGHD, MAKH, KHUYENMAI)
VALUES
('00001', '22/11/2017', 'KH01', 5),
('00002', '04/12/2017', 'KH03', 5),
('00003', '10/12/2017', 'KH02', 10);

INSERT INTO CTHD(SOHD, MALC, SOLUONG)
VALUES
('00001', 'LC01', 1),
('00001', 'LC02', 2),
('00003', 'LC03', 5);

-- CAU 3 --
ALTER TABLE LOAICAY ADD CONSTRAINT KT_XUATXU CHECK ((XUATXU != 'Anh') OR (XUATXU = 'Anh' AND GIA > 250000))

-- CAU 4 --
CREATE TRIGGER ins_up_CAU4 ON CTHD
FOR INSERT, UPDATE
AS
BEGIN
	DECLARE @DEM INT
	DECLARE @SOHD CHAR(5)
	SELECT @SOHD = SOHD FROM INSERTED
	SELECT @DEM = SUM(SOLUONG) FROM CTHD WHERE SOHD = @SOHD
	IF (@DEM >= 5)
	BEGIN
		UPDATE HOADON SET KHUYENMAI = 10 WHERE SOHD = @SOHD
	END
	ELSE
	BEGIN
		PRINT 'CHUA DU SO LUONG DE DUOC KHUYEN MAI'
		ROLLBACK TRAN
	END
END

-- CAU 5 --
SELECT * 
FROM HOADON 
WHERE YEAR(NGHD) = 2017 AND MONTH(NGHD) BETWEEN 10 AND 12
GROUP BY SOHDT
ORDER BY KHUYENMAI ASC

-- CAU 6 --
SELECT TOP 1 LOAICAY.MALC, SUM(SOLUONG) AS TOTAL
FROM LOAICAY
JOIN CTHD ON LOAICAY.MALC = CTHD.MALC
JOIN HOADON ON CTHD.SOHD = HOADON.SOHD
WHERE MONTH(NGHD) = 12
GROUP BY LOAICAY.MALC
ORDER BY SUM(SOLUONG) ASC
	
-- CAU 7 -- 
SELECT LOAICAY.MALC, TENLC
FROM LOAICAY
JOIN CTHD ON LOAICAY.MALC = CTHD.MALC
JOIN HOADON ON CTHD.SOHD = HOADON.SOHD
JOIN KHACHHANG ON HOADON.MAKH = KHACHHANG.MAKH
WHERE LOAIKH = 'Thuong xuyen'
INTERSECT
(
	SELECT LOAICAY.MALC, TENLC
	FROM LOAICAY
	JOIN CTHD ON LOAICAY.MALC = CTHD.MALC
	JOIN HOADON ON CTHD.SOHD = HOADON.SOHD
	JOIN KHACHHANG ON HOADON.MAKH = KHACHHANG.MAKH
	WHERE LOAIKH = 'Vang lai'
)

-- CAU 8 --
SELECT KHACHHANG.MAKH, TENKH
FROM KHACHHANG
JOIN HOADON ON KHACHHANG.MAKH = HOADON.MAKH
JOIN CTHD ON HOADON.SOHD = CTHD.SOHD
GROUP BY KHACHHANG.MAKH, TENKH
HAVING COUNT(DISTINCT CTHD.MALC) = ( SELECT COUNT(DISTINCT MALC)
									 FROM LOAICAY)

