CREATE DATABASE BAITHI
USE BAITHI

CREATE TABLE HLV
(
	MAHLV CHAR(6) NOT NULL,
	TENHLV VARCHAR(30),
	QUOCTICH VARCHAR(20),
	NGSINH SMALLDATETIME,
	CONSTRAINT HLV_PK PRIMARY KEY (MAHLV)
)

CREATE TABLE DOITUYEN 
(
	MADT CHAR(5) NOT NULL,
	MAHLV CHAR(6) NOT NULL,
	QUOCGIA VARCHAR(20),
	CHAULUC VARCHAR(15),
	DIEM INT,
	CONSTRAINT DT_PR PRIMARY KEY (MADT),
	CONSTRAINT DT_HLV_FK FOREIGN KEY (MAHLV) REFERENCES HLV(MAHLV)
)

CREATE TABLE FINALWC
(
	MAFWC CHAR(5) NOT NULL,
	NUOCTC VARCHAR(20),
	NAM INT,
	NGBD SMALLDATETIME,
	TONGKP INT,
	CONSTRAINT FINALWC_PK PRIMARY KEY (MAFWC)
)

CREATE TABLE KETQUA
(
	MAKQ CHAR(5) NOT NULL,
	MADT CHAR(5) NOT NULL,
	MAFWC CHAR(5) NOT NULL,
	TONGSOBT INT,
	THUHANG INT,
	HUYCHUONG CHAR(5),
	CONSTRAINT KQ_PK PRIMARY KEY (MAKQ),
	CONSTRAINT KQ_DT_FK FOREIGN KEY (MADT) REFERENCES DOITUYEN(MADT),
	CONSTRAINT KQ_FWC_FK FOREIGN KEY (MAFWC) REFERENCES FINALWC(MAFWC)
)


INSERT INTO HLV(MAHLV, TENHLV, QUOCTICH, NGSINH)
VALUES
('HLV001', 'Adenor Leonardo Bacchi', 'Brazil', '25/05/1961'),
('HLV002', 'Hansi Flick', 'Duc', '24/02/1965'),
('HLV003', 'Roberto Martínez', 'Tay Ban Nha', '13/07/1973');

INSERT INTO DOITUYEN(MADT, MAHLV, QUOCGIA, CHAULUC, DIEM)
VALUES
('DT001', 'HLV001', 'Brazil', 'Chau My', 243),
('DT002', 'HLV002', 'Duc', 'Chau Au', 222),
('DT003', 'HLV003', 'Bi', 'Chau Au', 72);

INSERT INTO FINALWC(MAFWC, NUOCTC, NAM, NGBD, TONGKP)
VALUES
('WC001', 'Qatar', 2022, '20/11/2022', 13),
('WC002', 'Nga', 2018, '14/6/2018', 8),
('WC003', 'Brazil', 2022, '12/06/2014', 7);

INSERT INTO KETQUA(MAKQ, MADT, MAFWC, TONGSOBT, THUHANG, HUYCHUONG)
VALUES
('KQ001', 'DT001', 'WC001', 10, 1, 'Vang'),
('KQ002', 'DT002', 'WC001', 9, 3, 'Bac'),
('KQ003', 'DT003', 'WC001', 3, 10, NULL);

-- Cau 3 -- 
ALTER TABLE KETQUA ADD CONSTRAINT KT_HC CHECK ((HUYCHUONG != NULL) OR (TONGSOBT < 2 AND THUHANG = 5 AND HUYCHUONG = NULL))

-- Cau 4 --
CREATE TRIGGER CAU4 ON FINALWC
FOR INSERT, UPDATE
AS
BEGIN
	DECLARE @NUOCTC VARCHAR(20)
	DECLARE @NAM INT
	DECLARE @DOITUYENNUOCTC VARCHAR(20)
	SELECT @NUOCTC = NUOCTC, @NAM = NAM FROM inserted
	SELECT @DOITUYENNUOCTC = QUOCGIA FROM DOITUYEN 
	JOIN KETQUA ON DOITUYEN.MADT = KETQUA.MADT 
	WHERE KETQUA.MAFWC = ( SELECT MAFWC FROM FINALWC WHERE NAM = @NAM)

	IF (@NUOCTC = @DOITUYENNUOCTC)
	BEGIN 
		PRINT 'THAO TAC THANH CONG'
	END
	ELSE
	BEGIN
		PRINT 'QUOC GIA TO CHUC PHAI CO DOI TUYEN THAM GIA WC'
		ROLLBACK TRAN
	END
END

-- Cau 5 --
SELECT HLV.MAHLV, HLV.TENHLV
FROM HLV 
JOIN DOITUYEN ON HLV.MAHLV = DOITUYEN.MAHLV
WHERE HLV.QUOCTICH != QUOCGIA

-- Cau 6 --
SELECT TOP 1 NUOCTC, COUNT(DISTINCT FINALWC.MAFWC) AS SOLANTOCHUCWC, COUNT(HUYCHUONG) AS SOLUONGHUYCHUONGVANG
FROM FINALWC
LEFT JOIN KETQUA ON FINALWC.MAFWC = KETQUA.MAFWC
WHERE HUYCHUONG = 'Vang'
GROUP BY NUOCTC
ORDER BY SOLANTOCHUCWC DESC, SOLUONGHUYCHUONGVANG ASC

-- Cau 7 --
SELECT HLV.MAHLV, TENHLV
FROM HLV
JOIN DOITUYEN ON HLV.MAHLV = DOITUYEN.MAHLV
JOIN KETQUA ON DOITUYEN.MADT = KETQUA.MADT 
WHERE HLV.QUOCTICH = QUOCGIA AND HUYCHUONG != 'Vang'
EXCEPT
(
	SELECT HLV.MAHLV, TENHLV
	FROM HLV
	JOIN DOITUYEN ON HLV.MAHLV = DOITUYEN.MAHLV
	JOIN KETQUA ON DOITUYEN.MADT = KETQUA.MADT 
	WHERE HLV.QUOCTICH = QUOCGIA AND HUYCHUONG != 'Vang'
)

-- Cau 8 --
SELECT HLV.MAHLV, TENHLV
FROM HLV
JOIN DOITUYEN ON HLV.MAHLV = DOITUYEN.MAHLV
JOIN KETQUA ON DOITUYEN.MADT = KETQUA.MADT
WHERE HUYCHUONG = 'Vang' AND DOITUYEN.CHAULUC = 'Chau Au'
GROUP BY HLV.MAHLV, TENHLV
HAVING COUNT(DISTINCT KETQUA.MADT) = ( SELECT COUNT(DISTINCT MADT)
									   FROM DOITUYEN
									   WHERE CHAULUC = 'Chau Au')
